Update README.md
Object#itself is available since ruby 2.2, not 2.0

```
2.1.5 :001 > itself
NameError: undefined local variable or method `itself' for main:Object
	from (irb):1
	from /Users/gordon/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
2.1.5 :002 >
```